version: '3'
services:
  #auth: 
  #  build:
  #    context: .
  #    dockerfile: deployment/api/Dockerfile
  #  ports:
  #    - "8080:8080"
  session_storage:
    image: "redis:alpine"
    hostname: "session_storage"
    ports:
      - "6379:6379"
  user_data:
    image: "postgres:alpine"
    restart: always
    environment:
      - POSTGRES_PASSWORD=Finalspecimangood7738
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cauterize
    ports:
      - "5432:5432"
    volumes:
      - ./db/initial-schema.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build:
      context: web/
      dockerfile: ../deployment/web/Dockerfile
    ports: 
      - "80:80"
